Database:
  # [MySQL]
  # Tipo: MySQL
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [MySQL + Connection pool (HikariCP)]
  # Tipo: MySQL-pooling
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [SQLite]
  # Tipo: SQLite
  # Path:      <Path do arquivo. Ex.: database.sql>
  Tipo: SQLite
  Path: database.sql

# Opções de geração de key do comando /gerarkey.
Geracao-key:
  Tamanho: 12
  Numeros: true
  Letras-minusculas: true
  Letras-maiusculas: true

# Opções do comando /verkeys.
Ver-keys:
  Mensagem-jogador:
    - '&fLista de keys do jogador &6@jogador:'
    - '@@keys'
    - ''
  Mensagem-pessoal:
    - '  &fLista de keys que &6você &fpossui:'
    - '@@keys'
    - ''
  Formato-key: '  &7- &e@key &8▶ @vip&f &f@tipo &7@duracao &f&n(@usos usos)'
  Mensagem-hover: '&7Clique para preparar ativação'

# Stackar (true) ou não (false) os grupos dos vips quando serem ativados.
# [OBS]
#   * Modificação não recomendada durante o andamento do servidor, caso
#   * a intenção seja alterar as permissões dos vips existentes.
#   * A opção é válida apenas pros vips ativados depois da modificação.
Stackar-vips: false

# Guardar (true) ou givar (false) os itens de ativação.
# Os itens irão ser salvos na base de dados, para logo serem colhidos
# pelo jogador pela aba de "Itens" do menu VIP (/vip).
# Caso não quiser guardar os itens, existe a opção pode apagar o iten
# do menu "vip.yml" para não gerar confusões.
Coleta-de-itens: true

# Delay em segundos para executar o comando /trocarvip.
# Utilizado para evitar a abuso de consultas.
Delay-trocar-vip: 10

# Reduzir o tempo do vip primario *junto* com os secundarios é dizer,
# contar o tempo do vip inativos como os inativos.
# Caso esteja em false, o único vip que ira contar é o primario.
Reducao-simultanea: false

# O limite de keys que podem estar na venda de forma
# simultânea por um jogador.
Limite-de-keys-na-venda-por-jogador: 50