Database:
  # [MySQL]
  # Tipo: MySQL
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [MySQL + Connection pool (HikariCP)]
  # Tipo: MySQL-pooling
  # Url:       <Url do banco de dados>
  # Database:  <Nome do banco de dados>
  # Usuario:   <Nome de usuario>
  # Senha:     <Senha do usuario>
  #
  # [SQLite]
  # Tipo: SQLite
  # Path:      <Path do arquivo. Ex.: database.sql>
  Tipo: SQLite
  Path: database.sql

Geracao-key:
  Numeros: true
  Letras-minusculas: true
  Letras-maiusculas: true
# Opções do comando /verkeys
Ver-keys:
  Mensagem-jogador:
    - '&fLista de keys do jogador &6@jogador:'
    - '@@keys'
    - ''
  Mensagem-pessoal:
    - '&fLista de keys que &6você &fpossui:'
    - '@@keys'
    - ''
  Formato-key: ' &7- &e@key &7: @vip&f @tipo &7@duracao &f&n@usos&r'