name: WorldVIP
main: com.worldplugins.vip.WorldVIP
version: 1.0
authors: [PostDev]
api-version: 1.8
commands:
  vip:
    description: Comando para operações gerais. Abre um GUI de gerenciamento caso executar sem argumentos
  criarkey:
    description: Cria uma key com os parametros indicados
  removerkey:
    description: Remover uma key (invalidar)
  verkeys:
    description: Mostrar a lista de keys do jogador ou de alguem mais (online)
  usarkey:
    description: Usar uma key. Ativa um vip
  tempovip:
    description: Mostrar o tempo vip do jogador ou de alguem mais (online)
  darvip:
    description: Giva um vip para um jogador
  setarvip:
    description: Setar o vip de um jogador online
  removervip:
    description: Remover vip/s de um jogador online
  trocarvip:
    description: Trocar o vip ativo por outro secondario